### ISSUE TITLE
 unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by ghost** [kurozael/twitter-contest-bot#19]
I get this issue when I run the script, here's the full stack trace:

`  File "main.py", line 61
    global ratelimit
                    ^
IndentationError: unindent does not match any outer indentation level
`

**Comment by AuxProc** [comment]
Looks like maybe just a spaces versus tabs issue with the file, or you made an edit after downloading and did not realize you changed the type of indent.  Feel free to try my twitter contest bot as well if you would like: https://github.com/ModusVivendi/twitter-contest
