### ISSUE TITLE
Getting Error while executing the code - 

### ISSUE THREAD

**Issue by bangash** [kurozael/twitter-contest-bot#21]
Message	File Name	Line	Position	
Traceback				
    <module>	C:\Python27\twitter-contest-bot-master\twitter-contest-bot-master\main.py	242		
    ScanForContests	C:\Python27\twitter-contest-bot-master\twitter-contest-bot-master\main.py	235		
TypeError: cannot concatenate 'str' and 'exceptions.UnboundLocalError' objects		

![image](https://user-images.githubusercontent.com/114377/26955094-fa4580a0-4ccd-11e7-9651-89b0df17522e.png)

Please guide

**Comment by IPFR33LY** [comment]
Convert object to string...

str(e)
