### ISSUE TITLE
.gitignore needs to ignore `log` and `config.json.example`

### ISSUE THREAD

**Issue by kurozael** [kurozael/twitter-contest-bot#26]
The `log` and the `config.json.example` should be ignored by `.gitignore`, so `config.json` should probably be renamed once again to `config.json.example`.

Do you think you may be able to fix this @forddasav? I've merged in your latest contribution but forgot to check these.

Thanks! 👍

**Comment by fheilz** [comment]
Okay I will change that and then re submit

**Comment by fheilz** [comment]
Not sure what you want, the .gitignore already have log and config.json.example. What should be renamed?

@kurozael
